# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: OTEyN2RiMjBhZTRkZjM2MGYzM2UwOTM1Mzg5MzM2NGEyNzM1MTQwMjdhNjdhMGYwMTY0ZDFlNjhhYzVlZTU0YzA1N2ZkYmYzYjEwMzY2NGRlYTA4ZTdiN2YxN2M3ZjIzYjEyY2U5NjQ3NTEzYmVlMjg0Y2I2OWMxNzUzNjNjZjc=
