# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NWI1NmI3YmQwMjU0NzMxMGE5YTJiM2Y2MTUxODFmYzBkOTFlZTQ1ZmVlNjg1NzU1ODQwOGEwZWFmNjA5NTg1ZTIzYWFjZTcyODc2OTMwMzk1OWIyYzJlZDIxZDM0NGQ5MDcwZDk2NGE2YzczMDM1ZTk2MTU5Y2RiZDVhYjk1NWI=
