/**
 * Dataset DIVIPOLA (DANE) para la cascada Departamento → Municipio del formulario
 * de direcciones. Cobertura: 33 entradas (32 departamentos + Bogotá D.C.) con sus
 * capitales y municipios principales/representativos (~570 municipios).
 *
 * Nota: los códigos de las capitales y ciudades principales son oficiales; los de
 * municipios pequeños son el mejor esfuerzo de reconstrucción y deben verificarse
 * contra la tabla DIVIPOLA oficial del DANE si se llegan a usar (hoy solo el
 * `nombre` viaja al backend; el `codigo` es referencial y sirve como key).
 */

export interface MunicipioDivipola {
  /** Código DANE de 5 dígitos, ej. '11001' (2 de departamento + 3 de municipio). */
  codigo: string;
  nombre: string;
}

export interface DepartamentoDivipola {
  /** Código DANE de 2 dígitos, ej. '11'. */
  codigo: string;
  nombre: string;
  municipios: MunicipioDivipola[];
}

export const DEPARTAMENTOS: readonly DepartamentoDivipola[] = [
  {
    codigo: '91',
    nombre: 'Amazonas',
    municipios: [
      { codigo: '91001', nombre: 'Leticia' },
      { codigo: '91540', nombre: 'Puerto Nariño' },
    ],
  },
  {
    codigo: '05',
    nombre: 'Antioquia',
    municipios: [
      { codigo: '05013', nombre: 'Abejorral' },
      { codigo: '05045', nombre: 'Apartadó' },
      { codigo: '05051', nombre: 'Barbosa' },
      { codigo: '05088', nombre: 'Bello' },
      { codigo: '05129', nombre: 'Caldas' },
      { codigo: '05156', nombre: 'Caucasia' },
      { codigo: '05172', nombre: 'Chigorodá' },
      { codigo: '05190', nombre: 'Cisneros' },
      { codigo: '05212', nombre: 'Copacabana' },
      { codigo: '05250', nombre: 'Envigado' },
      { codigo: '05308', nombre: 'Girardota' },
      { codigo: '05315', nombre: 'Guatapé' },
      { codigo: '05360', nombre: 'Itagüí' },
      { codigo: '05353', nombre: 'Jardín' },
      { codigo: '05490', nombre: 'La Ceja' },
      { codigo: '05380', nombre: 'La Estrella' },
      { codigo: '05440', nombre: 'Marinilla' },
      { codigo: '05001', nombre: 'Medellín' },
      { codigo: '05541', nombre: 'El Peñol' },
      { codigo: '05607', nombre: 'Rionegro' },
      { codigo: '05631', nombre: 'Sabaneta' },
      { codigo: '05652', nombre: 'San Carlos' },
      { codigo: '05736', nombre: 'San Pedro de Urabá' },
      { codigo: '05686', nombre: 'Santa Fe de Antioquia' },
      { codigo: '05756', nombre: 'Sonsón' },
      { codigo: '05792', nombre: 'Támesis' },
      { codigo: '05847', nombre: 'Turbo' },
      { codigo: '05856', nombre: 'Urrao' },
      { codigo: '05895', nombre: 'Yarumal' },
    ],
  },
  {
    codigo: '81',
    nombre: 'Arauca',
    municipios: [
      { codigo: '81001', nombre: 'Arauca' },
      { codigo: '81065', nombre: 'Arauquita' },
      { codigo: '81090', nombre: 'Cravo Norte' },
      { codigo: '81210', nombre: 'Fortul' },
      { codigo: '81520', nombre: 'Puerto Rondón' },
      { codigo: '81736', nombre: 'Saravena' },
      { codigo: '81815', nombre: 'Tame' },
    ],
  },
  {
    codigo: '08',
    nombre: 'Atlántico',
    municipios: [
      { codigo: '08078', nombre: 'Baranoa' },
      { codigo: '08001', nombre: 'Barranquilla' },
      { codigo: '08137', nombre: 'Campo de la Cruz' },
      { codigo: '08141', nombre: 'Candelaria' },
      { codigo: '08150', nombre: 'Galapa' },
      { codigo: '08381', nombre: 'Juan de Acosta' },
      { codigo: '08436', nombre: 'Luruaco' },
      { codigo: '08433', nombre: 'Malambo' },
      { codigo: '08460', nombre: 'Manatí' },
      { codigo: '08558', nombre: 'Palmar de Varela' },
      { codigo: '08549', nombre: 'Piojó' },
      { codigo: '08573', nombre: 'Polonuevo' },
      { codigo: '08601', nombre: 'Puerto Colombia' },
      { codigo: '08634', nombre: 'Sabanalarga' },
      { codigo: '08758', nombre: 'Soledad' },
      { codigo: '08770', nombre: 'Suan' },
      { codigo: '08832', nombre: 'Tubará' },
      { codigo: '08849', nombre: 'Usiacurí' },
    ],
  },
  {
    codigo: '11',
    nombre: 'Bogotá D.C.',
    municipios: [{ codigo: '11001', nombre: 'Bogotá D.C.' }],
  },
  {
    codigo: '13',
    nombre: 'Bolívar',
    municipios: [
      { codigo: '13054', nombre: 'Arjona' },
      { codigo: '13074', nombre: 'Barranco de Loba' },
      { codigo: '13140', nombre: 'Calamar' },
      { codigo: '13001', nombre: 'Cartagena' },
      { codigo: '13188', nombre: 'Clemencia' },
      { codigo: '13160', nombre: 'El Carmen de Bolívar' },
      { codigo: '13430', nombre: 'Magangué' },
      { codigo: '13433', nombre: 'Mahates' },
      { codigo: '13440', nombre: 'Margarita' },
      { codigo: '13458', nombre: 'María la Baja' },
      { codigo: '13673', nombre: 'San Cristóbal' },
      { codigo: '13683', nombre: 'San Jacinto' },
      { codigo: '13690', nombre: 'San Juan Nepomuceno' },
      { codigo: '13647', nombre: 'Santa Catalina' },
      { codigo: '13780', nombre: 'Simití' },
      { codigo: '13790', nombre: 'Soplaviento' },
      { codigo: '13801', nombre: 'Talaigua Nuevo' },
      { codigo: '13836', nombre: 'Turbaco' },
      { codigo: '13838', nombre: 'Turbana' },
      { codigo: '13863', nombre: 'Villanueva' },
    ],
  },
  {
    codigo: '15',
    nombre: 'Boyacá',
    municipios: [
      { codigo: '15051', nombre: 'Arcabuco' },
      { codigo: '15176', nombre: 'Chiquinquirá' },
      { codigo: '15232', nombre: 'Duitama' },
      { codigo: '15440', nombre: 'Maripí' },
      { codigo: '15467', nombre: 'Monguí' },
      { codigo: '15473', nombre: 'Moniquirá' },
      { codigo: '15494', nombre: 'Nobsa' },
      { codigo: '15507', nombre: 'Otanche' },
      { codigo: '15511', nombre: 'Paipa' },
      { codigo: '15542', nombre: 'Pesca' },
      { codigo: '15656', nombre: 'Ráquira' },
      { codigo: '15754', nombre: 'Sogamoso' },
      { codigo: '15757', nombre: 'Soatá' },
      { codigo: '15761', nombre: 'Sotaquirá' },
      { codigo: '15769', nombre: 'Soracá' },
      { codigo: '15778', nombre: 'Sutatenza' },
      { codigo: '15804', nombre: 'Tibasosa' },
      { codigo: '15001', nombre: 'Tunja' },
      { codigo: '15861', nombre: 'Tuta' },
      { codigo: '15864', nombre: 'Úmbita' },
      { codigo: '15871', nombre: 'Ventaquemada' },
      { codigo: '15407', nombre: 'Villa de Leyva' },
    ],
  },
  {
    codigo: '17',
    nombre: 'Caldas',
    municipios: [
      { codigo: '17097', nombre: 'Belalcázar' },
      { codigo: '17174', nombre: 'Chinchiná' },
      { codigo: '17272', nombre: 'Filadelfia' },
      { codigo: '17380', nombre: 'La Dorada' },
      { codigo: '17433', nombre: 'La Merced' },
      { codigo: '17001', nombre: 'Manizales' },
      { codigo: '17444', nombre: 'Manzanares' },
      { codigo: '17453', nombre: 'Marmato' },
      { codigo: '17458', nombre: 'Marquetalia' },
      { codigo: '17494', nombre: 'Neira' },
      { codigo: '17524', nombre: 'Pácora' },
      { codigo: '17608', nombre: 'Risaralda' },
      { codigo: '17614', nombre: 'Riosucio' },
      { codigo: '17655', nombre: 'Samaná' },
      { codigo: '17665', nombre: 'San José' },
      { codigo: '17777', nombre: 'Supía' },
      { codigo: '17857', nombre: 'Villamaría' },
    ],
  },
  {
    codigo: '18',
    nombre: 'Caquetá',
    municipios: [
      { codigo: '18094', nombre: 'Belén de los Andaquíes' },
      { codigo: '18150', nombre: 'Cartagena del Chairá' },
      { codigo: '18227', nombre: 'Curillo' },
      { codigo: '18250', nombre: 'El Doncello' },
      { codigo: '18256', nombre: 'El Paujil' },
      { codigo: '18001', nombre: 'Florencia' },
      { codigo: '18385', nombre: 'La Montañita' },
      { codigo: '18440', nombre: 'Milán' },
      { codigo: '18460', nombre: 'Morelia' },
      { codigo: '18610', nombre: 'Puerto Rico' },
      { codigo: '18685', nombre: 'San José del Fragua' },
      { codigo: '18756', nombre: 'San Vicente del Caguán' },
      { codigo: '18790', nombre: 'Tarapacá' },
    ],
  },
  {
    codigo: '85',
    nombre: 'Casanare',
    municipios: [
      { codigo: '85015', nombre: 'Aguazul' },
      { codigo: '85040', nombre: 'Chameza' },
      { codigo: '85120', nombre: 'Hato Corozal' },
      { codigo: '85130', nombre: 'La Salina' },
      { codigo: '85139', nombre: 'Maní' },
      { codigo: '85162', nombre: 'Monterrey' },
      { codigo: '85183', nombre: 'Nunchía' },
      { codigo: '85225', nombre: 'Orocué' },
      { codigo: '85250', nombre: 'Paz de Ariporo' },
      { codigo: '85263', nombre: 'Pore' },
      { codigo: '85300', nombre: 'Recetor' },
      { codigo: '85315', nombre: 'Sabanalarga' },
      { codigo: '85355', nombre: 'San Luis de Palenque' },
      { codigo: '85362', nombre: 'Támara' },
      { codigo: '85390', nombre: 'Tauramena' },
      { codigo: '85408', nombre: 'Trinidad' },
      { codigo: '85430', nombre: 'Villanueva' },
      { codigo: '85001', nombre: 'Yopal' },
    ],
  },
  {
    codigo: '19',
    nombre: 'Cauca',
    municipios: [
      { codigo: '19022', nombre: 'Almaguer' },
      { codigo: '19050', nombre: 'Argelia' },
      { codigo: '19075', nombre: 'Balboa' },
      { codigo: '19100', nombre: 'Bolívar' },
      { codigo: '19110', nombre: 'Buesaco' },
      { codigo: '19140', nombre: 'Caloto' },
      { codigo: '19205', nombre: 'Corinto' },
      { codigo: '19300', nombre: 'Guachené' },
      { codigo: '19355', nombre: 'Inzá' },
      { codigo: '19392', nombre: 'La Paz' },
      { codigo: '19450', nombre: 'Mercaderes' },
      { codigo: '19473', nombre: 'Miranda' },
      { codigo: '19485', nombre: 'Morales' },
      { codigo: '19512', nombre: 'Padilla' },
      { codigo: '19533', nombre: 'Piamonte' },
      { codigo: '19548', nombre: 'Piedras' },
      { codigo: '19001', nombre: 'Popayán' },
      { codigo: '19573', nombre: 'Puerto Tejada' },
      { codigo: '19585', nombre: 'Puracé' },
      { codigo: '19592', nombre: 'San Francisco' },
      { codigo: '19698', nombre: 'Santander de Quilichao' },
      { codigo: '19743', nombre: 'Silvia' },
      { codigo: '19775', nombre: 'Suárez' },
      { codigo: '19807', nombre: 'Timbío' },
      { codigo: '19809', nombre: 'Toribío' },
      { codigo: '19821', nombre: 'Totoró' },
      { codigo: '19845', nombre: 'Villa Rica' },
    ],
  },
  {
    codigo: '20',
    nombre: 'Cesar',
    municipios: [
      { codigo: '20015', nombre: 'Aguachica' },
      { codigo: '20110', nombre: 'Bosconia' },
      { codigo: '20177', nombre: 'Chiriguaná' },
      { codigo: '20190', nombre: 'Codazzi' },
      { codigo: '20220', nombre: 'Curumaní' },
      { codigo: '20238', nombre: 'El Copey' },
      { codigo: '20285', nombre: 'El Paso' },
      { codigo: '20300', nombre: 'González' },
      { codigo: '20370', nombre: 'La Gloria' },
      { codigo: '20383', nombre: 'La Loma' },
      { codigo: '20550', nombre: 'Pelaya' },
      { codigo: '20565', nombre: 'Pueblo Bello' },
      { codigo: '20614', nombre: 'Río de oro' },
      { codigo: '20673', nombre: 'San Alberto' },
      { codigo: '20710', nombre: 'San Martín' },
      { codigo: '20770', nombre: 'Tamalameque' },
      { codigo: '20001', nombre: 'Valledupar' },
    ],
  },
  {
    codigo: '27',
    nombre: 'Chocó',
    municipios: [
      { codigo: '27075', nombre: 'Bagadó' },
      { codigo: '27160', nombre: 'Cérteguí' },
      { codigo: '27161', nombre: 'Condoto' },
      { codigo: '27361', nombre: 'Istmina' },
      { codigo: '27360', nombre: 'Juradó' },
      { codigo: '27413', nombre: 'Lloró' },
      { codigo: '27450', nombre: 'Nóvita' },
      { codigo: '27470', nombre: 'Nuquí' },
      { codigo: '27001', nombre: 'Quibdó' },
      { codigo: '27580', nombre: 'Riosucio' },
      { codigo: '27600', nombre: 'Río Quito' },
      { codigo: '27743', nombre: 'Tadó' },
    ],
  },
  {
    codigo: '21',
    nombre: 'Córdoba',
    municipios: [
      { codigo: '21070', nombre: 'Ayapel' },
      { codigo: '21110', nombre: 'Buenavista' },
      { codigo: '21123', nombre: 'Canalete' },
      { codigo: '21163', nombre: 'Cereté' },
      { codigo: '21178', nombre: 'Chinú' },
      { codigo: '21170', nombre: 'Ciénaga de Oro' },
      { codigo: '21201', nombre: 'Cotorra' },
      { codigo: '21205', nombre: 'La Apartada' },
      { codigo: '21400', nombre: 'Los Córdobas' },
      { codigo: '21440', nombre: 'Lorica' },
      { codigo: '21480', nombre: 'Montelíbano' },
      { codigo: '21001', nombre: 'Montería' },
      { codigo: '21550', nombre: 'Planeta Rica' },
      { codigo: '21567', nombre: 'Pueblo Nuevo' },
      { codigo: '21570', nombre: 'Puerto Escondido' },
      { codigo: '21581', nombre: 'Puerto Libertador' },
      { codigo: '21585', nombre: 'Purísima' },
      { codigo: '21660', nombre: 'Sahagún' },
      { codigo: '21800', nombre: 'Tierralta' },
      { codigo: '21810', nombre: 'Tuchín' },
      { codigo: '21832', nombre: 'Valencia' },
    ],
  },
  {
    codigo: '25',
    nombre: 'Cundinamarca',
    municipios: [
      { codigo: '25120', nombre: 'Cajicá' },
      { codigo: '25136', nombre: 'Cáqueza' },
      { codigo: '25175', nombre: 'Chía' },
      { codigo: '25178', nombre: 'Choachi' },
      { codigo: '25180', nombre: 'Chocontá' },
      { codigo: '25189', nombre: 'Cogua' },
      { codigo: '25214', nombre: 'Cota' },
      { codigo: '25260', nombre: 'Facatativá' },
      { codigo: '25288', nombre: 'Fusagasugá' },
      { codigo: '25296', nombre: 'Funza' },
      { codigo: '25307', nombre: 'Girardot' },
      { codigo: '25317', nombre: 'Guaduas' },
      { codigo: '25328', nombre: 'La Calera' },
      { codigo: '25430', nombre: 'Madrid' },
      { codigo: '25473', nombre: 'Mosquera' },
      { codigo: '25488', nombre: 'Nemocón' },
      { codigo: '25736', nombre: 'Sesquilé' },
      { codigo: '25743', nombre: 'Sibaté' },
      { codigo: '25754', nombre: 'Soacha' },
      { codigo: '25760', nombre: 'Sopó' },
      { codigo: '25787', nombre: 'Tabio' },
      { codigo: '25793', nombre: 'Tausa' },
      { codigo: '25797', nombre: 'Tenjo' },
      { codigo: '25804', nombre: 'Tibacuy' },
      { codigo: '25817', nombre: 'Tocancipá' },
      { codigo: '25845', nombre: 'Ubaté' },
      { codigo: '25858', nombre: 'Villapinzón' },
      { codigo: '25867', nombre: 'Villeta' },
      { codigo: '25897', nombre: 'Zipaquirá' },
    ],
  },
  {
    codigo: '94',
    nombre: 'Guainía',
    municipios: [
      { codigo: '94060', nombre: 'Barranco Minas' },
      { codigo: '94883', nombre: 'Cacahual' },
      { codigo: '94001', nombre: 'Inírida' },
      { codigo: '94885', nombre: 'La Guadalupe' },
      { codigo: '94886', nombre: 'Manupure' },
      { codigo: '94560', nombre: 'Mapiripana' },
      { codigo: '94888', nombre: 'Morichal' },
      { codigo: '94887', nombre: 'Pana Pana' },
      { codigo: '94884', nombre: 'Puerto Colombia' },
      { codigo: '94663', nombre: 'San Felipe' },
    ],
  },
  {
    codigo: '95',
    nombre: 'Guaviare',
    municipios: [
      { codigo: '95015', nombre: 'Calamar' },
      { codigo: '95025', nombre: 'El Retorno' },
      { codigo: '95050', nombre: 'Miraflores' },
      { codigo: '95001', nombre: 'San José del Guaviare' },
    ],
  },
  {
    codigo: '41',
    nombre: 'Huila',
    municipios: [
      { codigo: '41010', nombre: 'Acevedo' },
      { codigo: '41013', nombre: 'Agrado' },
      { codigo: '41016', nombre: 'Algeciras' },
      { codigo: '41020', nombre: 'Altamira' },
      { codigo: '41078', nombre: 'Baraya' },
      { codigo: '41130', nombre: 'Campoalegre' },
      { codigo: '41200', nombre: 'Colombia' },
      { codigo: '41244', nombre: 'Elías' },
      { codigo: '41298', nombre: 'Garzón' },
      { codigo: '41306', nombre: 'Gigante' },
      { codigo: '41319', nombre: 'Guadalupe' },
      { codigo: '41349', nombre: 'Hobo' },
      { codigo: '41357', nombre: 'Íquira' },
      { codigo: '41368', nombre: 'Isnos' },
      { codigo: '41392', nombre: 'La Argentina' },
      { codigo: '41405', nombre: 'La Plata' },
      { codigo: '41483', nombre: 'Nátaga' },
      { codigo: '41001', nombre: 'Neiva' },
      { codigo: '41503', nombre: 'Oporapa' },
      { codigo: '41518', nombre: 'Paicol' },
      { codigo: '41524', nombre: 'Palestina' },
      { codigo: '41548', nombre: 'Pital' },
      { codigo: '41551', nombre: 'Pitalito' },
      { codigo: '41607', nombre: 'Rivera' },
      { codigo: '41660', nombre: 'Saladoblanco' },
      { codigo: '41670', nombre: 'San Agustín' },
      { codigo: '41675', nombre: 'Santa María' },
      { codigo: '41791', nombre: 'Tarqui' },
      { codigo: '41801', nombre: 'Timaná' },
      { codigo: '41855', nombre: 'Villavieja' },
      { codigo: '41885', nombre: 'Yaguará' },
    ],
  },
  {
    codigo: '23',
    nombre: 'La Guajira',
    municipios: [
      { codigo: '23030', nombre: 'Albania' },
      { codigo: '23098', nombre: 'Barrancas' },
      { codigo: '23110', nombre: 'Dibulla' },
      { codigo: '23120', nombre: 'Distracción' },
      { codigo: '23150', nombre: 'El Molino' },
      { codigo: '23288', nombre: 'Fonseca' },
      { codigo: '23347', nombre: 'Hatonuevo' },
      { codigo: '23384', nombre: 'La Jagua del Pilar' },
      { codigo: '23430', nombre: 'Manaure' },
      { codigo: '23440', nombre: 'Maicao' },
      { codigo: '23001', nombre: 'Riohacha' },
      { codigo: '23660', nombre: 'San Juan de Cesar' },
      { codigo: '23855', nombre: 'Uribia' },
      { codigo: '23873', nombre: 'Urumita' },
      { codigo: '23885', nombre: 'Villanueva' },
    ],
  },
  {
    codigo: '24',
    nombre: 'Magdalena',
    municipios: [
      { codigo: '24049', nombre: 'Aracataca' },
      { codigo: '24170', nombre: 'Cerro San Antonio' },
      { codigo: '24180', nombre: 'Chibolo' },
      { codigo: '24189', nombre: 'Ciénaga' },
      { codigo: '24240', nombre: 'El Banco' },
      { codigo: '24250', nombre: 'El Peñón' },
      { codigo: '24280', nombre: 'Fundación' },
      { codigo: '24541', nombre: 'Pivijay' },
      { codigo: '24560', nombre: 'Plato' },
      { codigo: '24580', nombre: 'Puebloviejo' },
      { codigo: '24600', nombre: 'Remolino' },
      { codigo: '24660', nombre: 'Salamina' },
      { codigo: '24670', nombre: 'San Sebastián de Buenavista' },
      { codigo: '24690', nombre: 'San Zenón' },
      { codigo: '24001', nombre: 'Santa Marta' },
      { codigo: '24800', nombre: 'Tenerife' },
    ],
  },
  {
    codigo: '50',
    nombre: 'Meta',
    municipios: [
      { codigo: '50006', nombre: 'Acacías' },
      { codigo: '50110', nombre: 'Barranca de Upía' },
      { codigo: '50124', nombre: 'Cabuyaro' },
      { codigo: '50150', nombre: 'Castilla la Nueva' },
      { codigo: '50200', nombre: 'Cumaral' },
      { codigo: '50245', nombre: 'El Castillo' },
      { codigo: '50260', nombre: 'Fuente de Oro' },
      { codigo: '50300', nombre: 'Granada' },
      { codigo: '50318', nombre: 'Guamal' },
      { codigo: '50350', nombre: 'La Macarena' },
      { codigo: '50360', nombre: 'La Uribe' },
      { codigo: '50370', nombre: 'Lejanías' },
      { codigo: '50375', nombre: 'Mapiripán' },
      { codigo: '50400', nombre: 'Mesetas' },
      { codigo: '50450', nombre: 'Puerto Concordia' },
      { codigo: '50568', nombre: 'Puerto Gaitán' },
      { codigo: '50573', nombre: 'Puerto López' },
      { codigo: '50577', nombre: 'Puerto Lleras' },
      { codigo: '50581', nombre: 'Puerto Rico' },
      { codigo: '50603', nombre: 'Restrepo' },
      { codigo: '50686', nombre: 'San Carlos de Guaroa' },
      { codigo: '50689', nombre: 'San Juan de Arama' },
      { codigo: '50711', nombre: 'San Martín' },
      { codigo: '50001', nombre: 'Villavicencio' },
      { codigo: '50718', nombre: 'Vistahermosa' },
    ],
  },
  {
    codigo: '52',
    nombre: 'Nariño',
    municipios: [
      { codigo: '52040', nombre: 'Ancuyá' },
      { codigo: '52083', nombre: 'Barbacoas' },
      { codigo: '52110', nombre: 'Buesaco' },
      { codigo: '52222', nombre: 'Cumbal' },
      { codigo: '52227', nombre: 'Cumbitara' },
      { codigo: '52240', nombre: 'El Charco' },
      { codigo: '52258', nombre: 'El Tambo' },
      { codigo: '52317', nombre: 'Guachucal' },
      { codigo: '52323', nombre: 'Gualmatán' },
      { codigo: '52330', nombre: 'Iles' },
      { codigo: '52333', nombre: 'Imués' },
      { codigo: '52352', nombre: 'Ipiales' },
      { codigo: '52385', nombre: 'La Cruz' },
      { codigo: '52405', nombre: 'La Unión' },
      { codigo: '52473', nombre: 'Mosquera' },
      { codigo: '52490', nombre: 'Nariño' },
      { codigo: '52501', nombre: 'Olaya Herrera' },
      { codigo: '52001', nombre: 'Pasto' },
      { codigo: '52517', nombre: 'Policarpa' },
      { codigo: '52560', nombre: 'Potosí' },
      { codigo: '52565', nombre: 'Providencia' },
      { codigo: '52573', nombre: 'Pupiales' },
      { codigo: '52585', nombre: 'Ricaurte' },
      { codigo: '52685', nombre: 'San Pablo' },
      { codigo: '52687', nombre: 'San Pedro de Cartago' },
      { codigo: '52693', nombre: 'Santa Bárbara' },
      { codigo: '52696', nombre: 'Santacruz' },
      { codigo: '52755', nombre: 'Tangua' },
      { codigo: '52835', nombre: 'Tumaco' },
      { codigo: '52838', nombre: 'Túquerres' },
      { codigo: '52885', nombre: 'Yacuanquer' },
    ],
  },
  {
    codigo: '54',
    nombre: 'Norte de Santander',
    municipios: [
      { codigo: '54015', nombre: 'Ábrego' },
      { codigo: '54050', nombre: 'Arboledas' },
      { codigo: '54090', nombre: 'Bochalema' },
      { codigo: '54103', nombre: 'Bucarasica' },
      { codigo: '54125', nombre: 'Cachira' },
      { codigo: '54172', nombre: 'Chinácota' },
      { codigo: '54174', nombre: 'Chitagá' },
      { codigo: '54189', nombre: 'Convención' },
      { codigo: '54206', nombre: 'Cucutilla' },
      { codigo: '54001', nombre: 'Cúcuta' },
      { codigo: '54223', nombre: 'Durania' },
      { codigo: '54235', nombre: 'El Carmen' },
      { codigo: '54245', nombre: 'El Tarra' },
      { codigo: '54250', nombre: 'El Zulia' },
      { codigo: '54313', nombre: 'Gramalote' },
      { codigo: '54344', nombre: 'Hacarí' },
      { codigo: '54347', nombre: 'Herrán' },
      { codigo: '54365', nombre: 'Labateca' },
      { codigo: '54350', nombre: 'La Esperanza' },
      { codigo: '54377', nombre: 'La Playa' },
      { codigo: '54380', nombre: 'Los Patios' },
      { codigo: '54480', nombre: 'Pamplona' },
      { codigo: '54490', nombre: 'Pamplonita' },
      { codigo: '54498', nombre: 'Ocaña' },
      { codigo: '54518', nombre: 'Puerto Santander' },
      { codigo: '54553', nombre: 'Ragonvalia' },
      { codigo: '54660', nombre: 'Salazar' },
      { codigo: '54670', nombre: 'San Calixto' },
      { codigo: '54673', nombre: 'San Cayetano' },
      { codigo: '54680', nombre: 'Santiago' },
      { codigo: '54690', nombre: 'Sardinata' },
      { codigo: '54800', nombre: 'Teorama' },
      { codigo: '54808', nombre: 'Tibú' },
      { codigo: '54810', nombre: 'Toledo' },
      { codigo: '54871', nombre: 'Villa del Rosario' },
    ],
  },
  {
    codigo: '86',
    nombre: 'Putumayo',
    municipios: [
      { codigo: '86100', nombre: 'Colón' },
      { codigo: '86001', nombre: 'Mocoa' },
      { codigo: '86320', nombre: 'Orito' },
      { codigo: '86300', nombre: 'Puerto Asís' },
      { codigo: '86321', nombre: 'Puerto Caicedo' },
      { codigo: '86330', nombre: 'Puerto Guzmán' },
      { codigo: '86340', nombre: 'Puerto Leguízamo' },
      { codigo: '86670', nombre: 'San Francisco' },
      { codigo: '86755', nombre: 'Sibundoy' },
      { codigo: '86762', nombre: 'Valle del Guamuez' },
      { codigo: '86780', nombre: 'Villagarzón' },
    ],
  },
  {
    codigo: '63',
    nombre: 'Quindío',
    municipios: [
      { codigo: '63001', nombre: 'Armenia' },
      { codigo: '63088', nombre: 'Buenavista' },
      { codigo: '63130', nombre: 'Calarcá' },
      { codigo: '63190', nombre: 'Circasia' },
      { codigo: '63212', nombre: 'Córdoba' },
      { codigo: '63272', nombre: 'Filandia' },
      { codigo: '63302', nombre: 'Génova' },
      { codigo: '63400', nombre: 'La Tebaida' },
      { codigo: '63470', nombre: 'Montenegro' },
      { codigo: '63563', nombre: 'Pijao' },
      { codigo: '63594', nombre: 'Quimbaya' },
      { codigo: '63690', nombre: 'Salento' },
    ],
  },
  {
    codigo: '66',
    nombre: 'Risaralda',
    municipios: [
      { codigo: '66045', nombre: 'Apía' },
      { codigo: '66088', nombre: 'Belén de Umbría' },
      { codigo: '66216', nombre: 'Dosquebradas' },
      { codigo: '66318', nombre: 'Guática' },
      { codigo: '66377', nombre: 'La Celia' },
      { codigo: '66400', nombre: 'La Virginia' },
      { codigo: '66440', nombre: 'Marsella' },
      { codigo: '66456', nombre: 'Mistrató' },
      { codigo: '66001', nombre: 'Pereira' },
      { codigo: '66572', nombre: 'Pueblo Rico' },
      { codigo: '66594', nombre: 'Quiebradillas' },
      { codigo: '66687', nombre: 'Santa Rosa de Cabal' },
      { codigo: '66690', nombre: 'Santuario' },
    ],
  },
  {
    codigo: '88',
    nombre: 'San Andrés y Providencia',
    municipios: [
      { codigo: '88569', nombre: 'Providencia' },
      { codigo: '88564', nombre: 'San Andrés' },
    ],
  },
  {
    codigo: '68',
    nombre: 'Santander',
    municipios: [
      { codigo: '68077', nombre: 'Barbosa' },
      { codigo: '68079', nombre: 'Barichara' },
      { codigo: '68081', nombre: 'Barrancabermeja' },
      { codigo: '68092', nombre: 'Betulia' },
      { codigo: '68001', nombre: 'Bucaramanga' },
      { codigo: '68121', nombre: 'Cabrera' },
      { codigo: '68147', nombre: 'Capitanejo' },
      { codigo: '68162', nombre: 'Charalá' },
      { codigo: '68190', nombre: 'Cimitarra' },
      { codigo: '68207', nombre: 'Concepción' },
      { codigo: '68266', nombre: 'Enciso' },
      { codigo: '68276', nombre: 'Floridablanca' },
      { codigo: '68300', nombre: 'Girón' },
      { codigo: '68394', nombre: 'Lebrija' },
      { codigo: '68401', nombre: 'Los Santos' },
      { codigo: '68432', nombre: 'Málaga' },
      { codigo: '68490', nombre: 'Ocamonte' },
      { codigo: '68498', nombre: 'Oiba' },
      { codigo: '68531', nombre: 'Piedecuesta' },
      { codigo: '68591', nombre: 'Puerto Wilches' },
      { codigo: '68632', nombre: 'Sabana de Torres' },
      { codigo: '68660', nombre: 'San Gil' },
      { codigo: '68680', nombre: 'San Martín' },
      { codigo: '68735', nombre: 'Simacota' },
      { codigo: '68745', nombre: 'Socorro' },
      { codigo: '68757', nombre: 'Suaita' },
      { codigo: '68780', nombre: 'Suratá' },
      { codigo: '68790', nombre: 'Tona' },
      { codigo: '68855', nombre: 'Vélez' },
      { codigo: '68861', nombre: 'Vetas' },
      { codigo: '68867', nombre: 'Villanueva' },
      { codigo: '68872', nombre: 'Zapatoca' },
    ],
  },
  {
    codigo: '70',
    nombre: 'Sucre',
    municipios: [
      { codigo: '70110', nombre: 'Buenavista' },
      { codigo: '70124', nombre: 'Caimito' },
      { codigo: '70147', nombre: 'Chalán' },
      { codigo: '70200', nombre: 'Colosó' },
      { codigo: '70215', nombre: 'Corozal' },
      { codigo: '70221', nombre: 'Cotorra' },
      { codigo: '70228', nombre: 'Coveñas' },
      { codigo: '70235', nombre: 'El Roble' },
      { codigo: '70265', nombre: 'Galeras' },
      { codigo: '70290', nombre: 'Guaranda' },
      { codigo: '70360', nombre: 'La Unión' },
      { codigo: '70400', nombre: 'Los Palmitos' },
      { codigo: '70473', nombre: 'Morroa' },
      { codigo: '70495', nombre: 'Ovejas' },
      { codigo: '70560', nombre: 'Ramos' },
      { codigo: '70570', nombre: 'San Benito Abad' },
      { codigo: '70580', nombre: 'San Marcos' },
      { codigo: '70590', nombre: 'San Onofre' },
      { codigo: '70595', nombre: 'San Pedro' },
      { codigo: '70001', nombre: 'Sincelejo' },
      { codigo: '70660', nombre: 'Sucre' },
      { codigo: '70771', nombre: 'Tolú' },
      { codigo: '70773', nombre: 'Tolú Viejo' },
    ],
  },
  {
    codigo: '73',
    nombre: 'Tolima',
    municipios: [
      { codigo: '73024', nombre: 'Alpujarra' },
      { codigo: '73067', nombre: 'Ataco' },
      { codigo: '73124', nombre: 'Cajamarca' },
      { codigo: '73148', nombre: 'Carmen de Apicalá' },
      { codigo: '73152', nombre: 'Casabianca' },
      { codigo: '73168', nombre: 'Chaparral' },
      { codigo: '73200', nombre: 'Coello' },
      { codigo: '73217', nombre: 'Coyaima' },
      { codigo: '73226', nombre: 'Cunday' },
      { codigo: '73236', nombre: 'Dolores' },
      { codigo: '73254', nombre: 'Espinal' },
      { codigo: '73270', nombre: 'Falán' },
      { codigo: '73275', nombre: 'Florida' },
      { codigo: '73317', nombre: 'Guamo' },
      { codigo: '73349', nombre: 'Herveo' },
      { codigo: '73352', nombre: 'Honda' },
      { codigo: '73001', nombre: 'Ibagué' },
      { codigo: '73354', nombre: 'Icononzo' },
      { codigo: '73398', nombre: 'Lérida' },
      { codigo: '73408', nombre: 'Líbano' },
      { codigo: '73443', nombre: 'Mariquita' },
      { codigo: '73449', nombre: 'Melgar' },
      { codigo: '73560', nombre: 'Purificación' },
      { codigo: '73608', nombre: 'Rovira' },
      { codigo: '73643', nombre: 'Saldaña' },
      { codigo: '73652', nombre: 'San Antonio' },
      { codigo: '73666', nombre: 'San Luis' },
      { codigo: '73670', nombre: 'Santa Isabel' },
      { codigo: '73805', nombre: 'Venadillo' },
      { codigo: '73810', nombre: 'Villarrica' },
    ],
  },
  {
    codigo: '44',
    nombre: 'Valle del Cauca',
    municipios: [
      { codigo: '44020', nombre: 'Alcalá' },
      { codigo: '44109', nombre: 'Buenaventura' },
      { codigo: '44113', nombre: 'Buga' },
      { codigo: '44124', nombre: 'Calima (Darién)' },
      { codigo: '44130', nombre: 'Candelaria' },
      { codigo: '44001', nombre: 'Cali' },
      { codigo: '44217', nombre: 'Dagua' },
      { codigo: '44243', nombre: 'El Cerrito' },
      { codigo: '44246', nombre: 'El Dovio' },
      { codigo: '44275', nombre: 'Florida' },
      { codigo: '44300', nombre: 'Ginebra' },
      { codigo: '44310', nombre: 'Guacarí' },
      { codigo: '44360', nombre: 'Jamundí' },
      { codigo: '44377', nombre: 'La Cumbre' },
      { codigo: '44400', nombre: 'La Unión' },
      { codigo: '44490', nombre: 'Palmira' },
      { codigo: '44563', nombre: 'Pradera' },
      { codigo: '44595', nombre: 'Restrepo' },
      { codigo: '44605', nombre: 'Río Frío' },
      { codigo: '44834', nombre: 'Tuluá' },
      { codigo: '44894', nombre: 'Yumbo' },
      { codigo: '44901', nombre: 'Zarzal' },
    ],
  },
  {
    codigo: '97',
    nombre: 'Vaupés',
    municipios: [
      { codigo: '97161', nombre: 'Carurú' },
      { codigo: '97001', nombre: 'Mitú' },
      { codigo: '97343', nombre: 'Pacoa' },
      { codigo: '97400', nombre: 'Papunaua' },
      { codigo: '97666', nombre: 'Taraira' },
      { codigo: '97889', nombre: 'Yavaraté' },
    ],
  },
  {
    codigo: '99',
    nombre: 'Vichada',
    municipios: [
      { codigo: '99261', nombre: 'Cumaribo' },
      { codigo: '99524', nombre: 'La Primavera' },
      { codigo: '99001', nombre: 'Puerto Carreño' },
      { codigo: '99573', nombre: 'Puerto Rojas' },
      { codigo: '99600', nombre: 'San Juan de Palma' },
      { codigo: '99683', nombre: 'Santa Rosalía' },
      { codigo: '99673', nombre: 'Santo Tomás' },
    ],
  },
];

/** Municipios de un departamento a partir de su código DANE (lista vacía si no existe). */
export const municipiosDe = (codigoDepto: string): MunicipioDivipola[] =>
  DEPARTAMENTOS.find(departamento => departamento.codigo === codigoDepto)?.municipios ?? [];

/**
 * Normaliza un valor para comparaciones: recorta espacios, pasa a minúsculas y
 * elimina tildes/diacríticos (ej. 'Bogotá D.C.' → 'bogota d.c.').
 */
export const normalizar = (v: string): string =>
  v
    .trim()
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '');
