export enum UbicacionBodega {
  BODEGA_PRINCIPAL = 'BODEGA_PRINCIPAL',

  BODEGA_SECUNDARIA = 'BODEGA_SECUNDARIA',

  BODEGA_NORTE = 'BODEGA_NORTE',

  BODEGA_SUR = 'BODEGA_SUR',

  EXHIBICION = 'EXHIBICION',

  CONSIGNACION = 'CONSIGNACION',
}
