package com.mycompany.knstore.domain;

import static com.mycompany.knstore.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CarritoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarritoAllPropertiesEquals(Carrito expected, Carrito actual) {
        assertCarritoAutoGeneratedPropertiesEquals(expected, actual);
        assertCarritoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarritoAllUpdatablePropertiesEquals(Carrito expected, Carrito actual) {
        assertCarritoUpdatableFieldsEquals(expected, actual);
        assertCarritoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarritoAutoGeneratedPropertiesEquals(Carrito expected, Carrito actual) {
        assertThat(actual)
            .as("Verify Carrito auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarritoUpdatableFieldsEquals(Carrito expected, Carrito actual) {
        assertThat(actual)
            .as("Verify Carrito relevant properties")
            .satisfies(a ->
                assertThat(a.getSubtotal()).as("check subtotal").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSubtotal())
            )
            .satisfies(a ->
                assertThat(a.getFechaActualizacion()).as("check fechaActualizacion").isEqualTo(expected.getFechaActualizacion())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCarritoUpdatableRelationshipsEquals(Carrito expected, Carrito actual) {
        assertThat(actual)
            .as("Verify Carrito relationships")
            .satisfies(a -> assertThat(a.getCuenta()).as("check cuenta").isEqualTo(expected.getCuenta()));
    }
}
