package com.mycompany.knstore.domain;

import static com.mycompany.knstore.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CategoriaIVAAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaIVAAllPropertiesEquals(CategoriaIVA expected, CategoriaIVA actual) {
        assertCategoriaIVAAutoGeneratedPropertiesEquals(expected, actual);
        assertCategoriaIVAAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaIVAAllUpdatablePropertiesEquals(CategoriaIVA expected, CategoriaIVA actual) {
        assertCategoriaIVAUpdatableFieldsEquals(expected, actual);
        assertCategoriaIVAUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaIVAAutoGeneratedPropertiesEquals(CategoriaIVA expected, CategoriaIVA actual) {
        assertThat(actual)
            .as("Verify CategoriaIVA auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaIVAUpdatableFieldsEquals(CategoriaIVA expected, CategoriaIVA actual) {
        assertThat(actual)
            .as("Verify CategoriaIVA relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a ->
                assertThat(a.getPorcentaje())
                    .as("check porcentaje")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPorcentaje())
            )
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCategoriaIVAUpdatableRelationshipsEquals(CategoriaIVA expected, CategoriaIVA actual) {
        // empty method
    }
}
