package com.mycompany.knstore.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CuentaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuentaAllPropertiesEquals(Cuenta expected, Cuenta actual) {
        assertCuentaAutoGeneratedPropertiesEquals(expected, actual);
        assertCuentaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuentaAllUpdatablePropertiesEquals(Cuenta expected, Cuenta actual) {
        assertCuentaUpdatableFieldsEquals(expected, actual);
        assertCuentaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuentaAutoGeneratedPropertiesEquals(Cuenta expected, Cuenta actual) {
        assertThat(actual)
            .as("Verify Cuenta auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuentaUpdatableFieldsEquals(Cuenta expected, Cuenta actual) {
        assertThat(actual)
            .as("Verify Cuenta relevant properties")
            .satisfies(a -> assertThat(a.getNumDocumento()).as("check numDocumento").isEqualTo(expected.getNumDocumento()))
            .satisfies(a -> assertThat(a.getPrimerNombre()).as("check primerNombre").isEqualTo(expected.getPrimerNombre()))
            .satisfies(a -> assertThat(a.getSegundoNombre()).as("check segundoNombre").isEqualTo(expected.getSegundoNombre()))
            .satisfies(a -> assertThat(a.getPrimerApellido()).as("check primerApellido").isEqualTo(expected.getPrimerApellido()))
            .satisfies(a -> assertThat(a.getSegundoApellido()).as("check segundoApellido").isEqualTo(expected.getSegundoApellido()))
            .satisfies(a -> assertThat(a.getGenero()).as("check genero").isEqualTo(expected.getGenero()))
            .satisfies(a -> assertThat(a.getFechaNacimiento()).as("check fechaNacimiento").isEqualTo(expected.getFechaNacimiento()))
            .satisfies(a -> assertThat(a.getCelular()).as("check celular").isEqualTo(expected.getCelular()))
            .satisfies(a -> assertThat(a.getTelefono()).as("check telefono").isEqualTo(expected.getTelefono()))
            .satisfies(a -> assertThat(a.getFotoPerfil()).as("check fotoPerfil").isEqualTo(expected.getFotoPerfil()))
            .satisfies(a ->
                assertThat(a.getFotoPerfilContentType()).as("check fotoPerfil content type").isEqualTo(expected.getFotoPerfilContentType())
            )
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuentaUpdatableRelationshipsEquals(Cuenta expected, Cuenta actual) {
        assertThat(actual)
            .as("Verify Cuenta relationships")
            .satisfies(a -> assertThat(a.getTipoDocumento()).as("check tipoDocumento").isEqualTo(expected.getTipoDocumento()));
    }
}
