package com.mycompany.knstore.domain;

import static com.mycompany.knstore.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class EnvioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnvioAllPropertiesEquals(Envio expected, Envio actual) {
        assertEnvioAutoGeneratedPropertiesEquals(expected, actual);
        assertEnvioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnvioAllUpdatablePropertiesEquals(Envio expected, Envio actual) {
        assertEnvioUpdatableFieldsEquals(expected, actual);
        assertEnvioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnvioAutoGeneratedPropertiesEquals(Envio expected, Envio actual) {
        assertThat(actual)
            .as("Verify Envio auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnvioUpdatableFieldsEquals(Envio expected, Envio actual) {
        assertThat(actual)
            .as("Verify Envio relevant properties")
            .satisfies(a -> assertThat(a.getTransportadora()).as("check transportadora").isEqualTo(expected.getTransportadora()))
            .satisfies(a -> assertThat(a.getNumeroRastreo()).as("check numeroRastreo").isEqualTo(expected.getNumeroRastreo()))
            .satisfies(a -> assertThat(a.getTipoServicio()).as("check tipoServicio").isEqualTo(expected.getTipoServicio()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a ->
                assertThat(a.getCostoEnvio())
                    .as("check costoEnvio")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCostoEnvio())
            )
            .satisfies(a ->
                assertThat(a.getPesoKg()).as("check pesoKg").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPesoKg())
            )
            .satisfies(a ->
                assertThat(a.getValorDeclarado())
                    .as("check valorDeclarado")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getValorDeclarado())
            )
            .satisfies(a -> assertThat(a.getUrlRastreo()).as("check urlRastreo").isEqualTo(expected.getUrlRastreo()))
            .satisfies(a -> assertThat(a.getObservaciones()).as("check observaciones").isEqualTo(expected.getObservaciones()))
            .satisfies(a -> assertThat(a.getFechaDespacho()).as("check fechaDespacho").isEqualTo(expected.getFechaDespacho()))
            .satisfies(a ->
                assertThat(a.getFechaEntregaEstimada()).as("check fechaEntregaEstimada").isEqualTo(expected.getFechaEntregaEstimada())
            )
            .satisfies(a -> assertThat(a.getFechaEntrega()).as("check fechaEntrega").isEqualTo(expected.getFechaEntrega()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnvioUpdatableRelationshipsEquals(Envio expected, Envio actual) {
        assertThat(actual)
            .as("Verify Envio relationships")
            .satisfies(a -> assertThat(a.getPedido()).as("check pedido").isEqualTo(expected.getPedido()));
    }
}
