package com.mycompany.knstore.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EtiquetaProductoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtiquetaProductoAllPropertiesEquals(EtiquetaProducto expected, EtiquetaProducto actual) {
        assertEtiquetaProductoAutoGeneratedPropertiesEquals(expected, actual);
        assertEtiquetaProductoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtiquetaProductoAllUpdatablePropertiesEquals(EtiquetaProducto expected, EtiquetaProducto actual) {
        assertEtiquetaProductoUpdatableFieldsEquals(expected, actual);
        assertEtiquetaProductoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtiquetaProductoAutoGeneratedPropertiesEquals(EtiquetaProducto expected, EtiquetaProducto actual) {
        assertThat(actual)
            .as("Verify EtiquetaProducto auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtiquetaProductoUpdatableFieldsEquals(EtiquetaProducto expected, EtiquetaProducto actual) {
        assertThat(actual)
            .as("Verify EtiquetaProducto relevant properties")
            .satisfies(a -> assertThat(a.getEtiqueta()).as("check etiqueta").isEqualTo(expected.getEtiqueta()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtiquetaProductoUpdatableRelationshipsEquals(EtiquetaProducto expected, EtiquetaProducto actual) {
        assertThat(actual)
            .as("Verify EtiquetaProducto relationships")
            .satisfies(a -> assertThat(a.getProducto()).as("check producto").isEqualTo(expected.getProducto()));
    }
}
