package com.mycompany.knstore.domain;

import static com.mycompany.knstore.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class FacturaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacturaAllPropertiesEquals(Factura expected, Factura actual) {
        assertFacturaAutoGeneratedPropertiesEquals(expected, actual);
        assertFacturaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacturaAllUpdatablePropertiesEquals(Factura expected, Factura actual) {
        assertFacturaUpdatableFieldsEquals(expected, actual);
        assertFacturaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacturaAutoGeneratedPropertiesEquals(Factura expected, Factura actual) {
        assertThat(actual)
            .as("Verify Factura auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacturaUpdatableFieldsEquals(Factura expected, Factura actual) {
        assertThat(actual)
            .as("Verify Factura relevant properties")
            .satisfies(a -> assertThat(a.getPrefijo()).as("check prefijo").isEqualTo(expected.getPrefijo()))
            .satisfies(a -> assertThat(a.getCufe()).as("check cufe").isEqualTo(expected.getCufe()))
            .satisfies(a ->
                assertThat(a.getSubtotal()).as("check subtotal").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSubtotal())
            )
            .satisfies(a ->
                assertThat(a.getDescuentos())
                    .as("check descuentos")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDescuentos())
            )
            .satisfies(a ->
                assertThat(a.getBaseGravableIva())
                    .as("check baseGravableIva")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBaseGravableIva())
            )
            .satisfies(a ->
                assertThat(a.getValorIva()).as("check valorIva").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getValorIva())
            )
            .satisfies(a -> assertThat(a.getTotal()).as("check total").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTotal()))
            .satisfies(a -> assertThat(a.getNotasAdicionales()).as("check notasAdicionales").isEqualTo(expected.getNotasAdicionales()))
            .satisfies(a -> assertThat(a.getCodigoQr()).as("check codigoQr").isEqualTo(expected.getCodigoQr()))
            .satisfies(a -> assertThat(a.getEnviada()).as("check enviada").isEqualTo(expected.getEnviada()))
            .satisfies(a -> assertThat(a.getFechaEmision()).as("check fechaEmision").isEqualTo(expected.getFechaEmision()))
            .satisfies(a -> assertThat(a.getFechaVencimiento()).as("check fechaVencimiento").isEqualTo(expected.getFechaVencimiento()))
            .satisfies(a -> assertThat(a.getFechaEnvioEmail()).as("check fechaEnvioEmail").isEqualTo(expected.getFechaEnvioEmail()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacturaUpdatableRelationshipsEquals(Factura expected, Factura actual) {
        assertThat(actual)
            .as("Verify Factura relationships")
            .satisfies(a -> assertThat(a.getPago()).as("check pago").isEqualTo(expected.getPago()));
    }
}
