package com.mycompany.knstore.domain;

import static com.mycompany.knstore.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ItemCarritoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemCarritoAllPropertiesEquals(ItemCarrito expected, ItemCarrito actual) {
        assertItemCarritoAutoGeneratedPropertiesEquals(expected, actual);
        assertItemCarritoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemCarritoAllUpdatablePropertiesEquals(ItemCarrito expected, ItemCarrito actual) {
        assertItemCarritoUpdatableFieldsEquals(expected, actual);
        assertItemCarritoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemCarritoAutoGeneratedPropertiesEquals(ItemCarrito expected, ItemCarrito actual) {
        assertThat(actual)
            .as("Verify ItemCarrito auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemCarritoUpdatableFieldsEquals(ItemCarrito expected, ItemCarrito actual) {
        assertThat(actual)
            .as("Verify ItemCarrito relevant properties")
            .satisfies(a -> assertThat(a.getCantidad()).as("check cantidad").isEqualTo(expected.getCantidad()))
            .satisfies(a ->
                assertThat(a.getPrecioUnitario())
                    .as("check precioUnitario")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPrecioUnitario())
            )
            .satisfies(a ->
                assertThat(a.getSubtotal()).as("check subtotal").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSubtotal())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemCarritoUpdatableRelationshipsEquals(ItemCarrito expected, ItemCarrito actual) {
        assertThat(actual)
            .as("Verify ItemCarrito relationships")
            .satisfies(a -> assertThat(a.getCarrito()).as("check carrito").isEqualTo(expected.getCarrito()))
            .satisfies(a -> assertThat(a.getProducto()).as("check producto").isEqualTo(expected.getProducto()));
    }
}
