package com.mycompany.knstore.domain;

import static com.mycompany.knstore.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ItemPedidoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemPedidoAllPropertiesEquals(ItemPedido expected, ItemPedido actual) {
        assertItemPedidoAutoGeneratedPropertiesEquals(expected, actual);
        assertItemPedidoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemPedidoAllUpdatablePropertiesEquals(ItemPedido expected, ItemPedido actual) {
        assertItemPedidoUpdatableFieldsEquals(expected, actual);
        assertItemPedidoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemPedidoAutoGeneratedPropertiesEquals(ItemPedido expected, ItemPedido actual) {
        assertThat(actual)
            .as("Verify ItemPedido auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemPedidoUpdatableFieldsEquals(ItemPedido expected, ItemPedido actual) {
        assertThat(actual)
            .as("Verify ItemPedido relevant properties")
            .satisfies(a -> assertThat(a.getNombreProducto()).as("check nombreProducto").isEqualTo(expected.getNombreProducto()))
            .satisfies(a -> assertThat(a.getSlugProducto()).as("check slugProducto").isEqualTo(expected.getSlugProducto()))
            .satisfies(a -> assertThat(a.getMarcaProducto()).as("check marcaProducto").isEqualTo(expected.getMarcaProducto()))
            .satisfies(a -> assertThat(a.getSkuProducto()).as("check skuProducto").isEqualTo(expected.getSkuProducto()))
            .satisfies(a -> assertThat(a.getColorProducto()).as("check colorProducto").isEqualTo(expected.getColorProducto()))
            .satisfies(a -> assertThat(a.getTallaProducto()).as("check tallaProducto").isEqualTo(expected.getTallaProducto()))
            .satisfies(a -> assertThat(a.getCantidad()).as("check cantidad").isEqualTo(expected.getCantidad()))
            .satisfies(a ->
                assertThat(a.getPrecioUnitario())
                    .as("check precioUnitario")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPrecioUnitario())
            )
            .satisfies(a ->
                assertThat(a.getPorcentajeIva())
                    .as("check porcentajeIva")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPorcentajeIva())
            )
            .satisfies(a ->
                assertThat(a.getValorIva()).as("check valorIva").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getValorIva())
            )
            .satisfies(a ->
                assertThat(a.getDescuento()).as("check descuento").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getDescuento())
            )
            .satisfies(a ->
                assertThat(a.getSubtotal()).as("check subtotal").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSubtotal())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertItemPedidoUpdatableRelationshipsEquals(ItemPedido expected, ItemPedido actual) {
        assertThat(actual)
            .as("Verify ItemPedido relationships")
            .satisfies(a -> assertThat(a.getPedido()).as("check pedido").isEqualTo(expected.getPedido()))
            .satisfies(a -> assertThat(a.getProducto()).as("check producto").isEqualTo(expected.getProducto()));
    }
}
