package com.mycompany.knstore.domain;

import static com.mycompany.knstore.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PedidoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPedidoAllPropertiesEquals(Pedido expected, Pedido actual) {
        assertPedidoAutoGeneratedPropertiesEquals(expected, actual);
        assertPedidoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPedidoAllUpdatablePropertiesEquals(Pedido expected, Pedido actual) {
        assertPedidoUpdatableFieldsEquals(expected, actual);
        assertPedidoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPedidoAutoGeneratedPropertiesEquals(Pedido expected, Pedido actual) {
        assertThat(actual)
            .as("Verify Pedido auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPedidoUpdatableFieldsEquals(Pedido expected, Pedido actual) {
        assertThat(actual)
            .as("Verify Pedido relevant properties")
            .satisfies(a -> assertThat(a.getNumeroPedido()).as("check numeroPedido").isEqualTo(expected.getNumeroPedido()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a ->
                assertThat(a.getSubtotal()).as("check subtotal").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSubtotal())
            )
            .satisfies(a ->
                assertThat(a.getDescuento()).as("check descuento").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getDescuento())
            )
            .satisfies(a ->
                assertThat(a.getIvaTotal()).as("check ivaTotal").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getIvaTotal())
            )
            .satisfies(a ->
                assertThat(a.getCostoEnvio())
                    .as("check costoEnvio")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCostoEnvio())
            )
            .satisfies(a -> assertThat(a.getTotal()).as("check total").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTotal()))
            .satisfies(a -> assertThat(a.getNotasCliente()).as("check notasCliente").isEqualTo(expected.getNotasCliente()))
            .satisfies(a -> assertThat(a.getNotasInternas()).as("check notasInternas").isEqualTo(expected.getNotasInternas()))
            .satisfies(a -> assertThat(a.getIpOrigen()).as("check ipOrigen").isEqualTo(expected.getIpOrigen()))
            .satisfies(a -> assertThat(a.getUserAgent()).as("check userAgent").isEqualTo(expected.getUserAgent()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPedidoUpdatableRelationshipsEquals(Pedido expected, Pedido actual) {
        assertThat(actual)
            .as("Verify Pedido relationships")
            .satisfies(a -> assertThat(a.getDireccion()).as("check direccion").isEqualTo(expected.getDireccion()))
            .satisfies(a -> assertThat(a.getCuenta()).as("check cuenta").isEqualTo(expected.getCuenta()));
    }
}
