package com.mycompany.knstore.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProductoImagenAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductoImagenAllPropertiesEquals(ProductoImagen expected, ProductoImagen actual) {
        assertProductoImagenAutoGeneratedPropertiesEquals(expected, actual);
        assertProductoImagenAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductoImagenAllUpdatablePropertiesEquals(ProductoImagen expected, ProductoImagen actual) {
        assertProductoImagenUpdatableFieldsEquals(expected, actual);
        assertProductoImagenUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductoImagenAutoGeneratedPropertiesEquals(ProductoImagen expected, ProductoImagen actual) {
        assertThat(actual)
            .as("Verify ProductoImagen auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductoImagenUpdatableFieldsEquals(ProductoImagen expected, ProductoImagen actual) {
        assertThat(actual)
            .as("Verify ProductoImagen relevant properties")
            .satisfies(a -> assertThat(a.getImagen()).as("check imagen").isEqualTo(expected.getImagen()))
            .satisfies(a -> assertThat(a.getImagenContentType()).as("check imagen content type").isEqualTo(expected.getImagenContentType()))
            .satisfies(a -> assertThat(a.getImagenAlt()).as("check imagenAlt").isEqualTo(expected.getImagenAlt()))
            .satisfies(a -> assertThat(a.getEsPrincipal()).as("check esPrincipal").isEqualTo(expected.getEsPrincipal()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductoImagenUpdatableRelationshipsEquals(ProductoImagen expected, ProductoImagen actual) {
        assertThat(actual)
            .as("Verify ProductoImagen relationships")
            .satisfies(a -> assertThat(a.getProducto()).as("check producto").isEqualTo(expected.getProducto()));
    }
}
