package com.mycompany.knstore.domain;

import static com.mycompany.knstore.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ProductoPrecioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductoPrecioAllPropertiesEquals(ProductoPrecio expected, ProductoPrecio actual) {
        assertProductoPrecioAutoGeneratedPropertiesEquals(expected, actual);
        assertProductoPrecioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductoPrecioAllUpdatablePropertiesEquals(ProductoPrecio expected, ProductoPrecio actual) {
        assertProductoPrecioUpdatableFieldsEquals(expected, actual);
        assertProductoPrecioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductoPrecioAutoGeneratedPropertiesEquals(ProductoPrecio expected, ProductoPrecio actual) {
        assertThat(actual)
            .as("Verify ProductoPrecio auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductoPrecioUpdatableFieldsEquals(ProductoPrecio expected, ProductoPrecio actual) {
        assertThat(actual)
            .as("Verify ProductoPrecio relevant properties")
            .satisfies(a ->
                assertThat(a.getPrecioCompra())
                    .as("check precioCompra")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPrecioCompra())
            )
            .satisfies(a ->
                assertThat(a.getPrecioVenta())
                    .as("check precioVenta")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPrecioVenta())
            )
            .satisfies(a ->
                assertThat(a.getPrecioAdicional())
                    .as("check precioAdicional")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPrecioAdicional())
            )
            .satisfies(a ->
                assertThat(a.getGanancia()).as("check ganancia").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getGanancia())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductoPrecioUpdatableRelationshipsEquals(ProductoPrecio expected, ProductoPrecio actual) {
        // empty method
    }
}
