package com.mycompany.knstore.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProductoInventarioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductoInventarioAllPropertiesEquals(ProductoInventario expected, ProductoInventario actual) {
        assertProductoInventarioAutoGeneratedPropertiesEquals(expected, actual);
        assertProductoInventarioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductoInventarioAllUpdatablePropertiesEquals(ProductoInventario expected, ProductoInventario actual) {
        assertProductoInventarioUpdatableFieldsEquals(expected, actual);
        assertProductoInventarioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductoInventarioAutoGeneratedPropertiesEquals(ProductoInventario expected, ProductoInventario actual) {
        assertThat(actual)
            .as("Verify ProductoInventario auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductoInventarioUpdatableFieldsEquals(ProductoInventario expected, ProductoInventario actual) {
        assertThat(actual)
            .as("Verify ProductoInventario relevant properties")
            .satisfies(a -> assertThat(a.getStock()).as("check stock").isEqualTo(expected.getStock()))
            .satisfies(a -> assertThat(a.getStockMinimo()).as("check stockMinimo").isEqualTo(expected.getStockMinimo()))
            .satisfies(a -> assertThat(a.getUbicacionBodega()).as("check ubicacionBodega").isEqualTo(expected.getUbicacionBodega()))
            .satisfies(a -> assertThat(a.getGarantiaMeses()).as("check garantiaMeses").isEqualTo(expected.getGarantiaMeses()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductoInventarioUpdatableRelationshipsEquals(ProductoInventario expected, ProductoInventario actual) {
        // empty method
    }
}
