package com.mycompany.knstore.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SubcategoriaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubcategoriaAllPropertiesEquals(Subcategoria expected, Subcategoria actual) {
        assertSubcategoriaAutoGeneratedPropertiesEquals(expected, actual);
        assertSubcategoriaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubcategoriaAllUpdatablePropertiesEquals(Subcategoria expected, Subcategoria actual) {
        assertSubcategoriaUpdatableFieldsEquals(expected, actual);
        assertSubcategoriaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubcategoriaAutoGeneratedPropertiesEquals(Subcategoria expected, Subcategoria actual) {
        assertThat(actual)
            .as("Verify Subcategoria auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubcategoriaUpdatableFieldsEquals(Subcategoria expected, Subcategoria actual) {
        assertThat(actual)
            .as("Verify Subcategoria relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getSlug()).as("check slug").isEqualTo(expected.getSlug()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getImagen()).as("check imagen").isEqualTo(expected.getImagen()))
            .satisfies(a -> assertThat(a.getImagenContentType()).as("check imagen content type").isEqualTo(expected.getImagenContentType()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubcategoriaUpdatableRelationshipsEquals(Subcategoria expected, Subcategoria actual) {
        assertThat(actual)
            .as("Verify Subcategoria relationships")
            .satisfies(a -> assertThat(a.getCategoria()).as("check categoria").isEqualTo(expected.getCategoria()));
    }
}
