package com.mycompany.knstore.domain;

import static com.mycompany.knstore.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class VarianteProductoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVarianteProductoAllPropertiesEquals(VarianteProducto expected, VarianteProducto actual) {
        assertVarianteProductoAutoGeneratedPropertiesEquals(expected, actual);
        assertVarianteProductoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVarianteProductoAllUpdatablePropertiesEquals(VarianteProducto expected, VarianteProducto actual) {
        assertVarianteProductoUpdatableFieldsEquals(expected, actual);
        assertVarianteProductoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVarianteProductoAutoGeneratedPropertiesEquals(VarianteProducto expected, VarianteProducto actual) {
        assertThat(actual)
            .as("Verify VarianteProducto auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVarianteProductoUpdatableFieldsEquals(VarianteProducto expected, VarianteProducto actual) {
        assertThat(actual)
            .as("Verify VarianteProducto relevant properties")
            .satisfies(a -> assertThat(a.getSku()).as("check sku").isEqualTo(expected.getSku()))
            .satisfies(a -> assertThat(a.getColor()).as("check color").isEqualTo(expected.getColor()))
            .satisfies(a -> assertThat(a.getTalla()).as("check talla").isEqualTo(expected.getTalla()))
            .satisfies(a -> assertThat(a.getCodigoBarras()).as("check codigoBarras").isEqualTo(expected.getCodigoBarras()))
            .satisfies(a -> assertThat(a.getStock()).as("check stock").isEqualTo(expected.getStock()))
            .satisfies(a -> assertThat(a.getStockMinimo()).as("check stockMinimo").isEqualTo(expected.getStockMinimo()))
            .satisfies(a -> assertThat(a.getUbicacionBodega()).as("check ubicacionBodega").isEqualTo(expected.getUbicacionBodega()))
            .satisfies(a ->
                assertThat(a.getPrecioAdicional())
                    .as("check precioAdicional")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPrecioAdicional())
            )
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVarianteProductoUpdatableRelationshipsEquals(VarianteProducto expected, VarianteProducto actual) {
        assertThat(actual)
            .as("Verify VarianteProducto relationships")
            .satisfies(a -> assertThat(a.getProducto()).as("check producto").isEqualTo(expected.getProducto()));
    }
}
